name       : cglm
version    : 0.8.3
release    : 2
source     :
    - https://github.com/recp/cglm/archive/refs/tags/v0.8.3.tar.gz : 3a3f935f9f2ed5a8cb6337e421bf6f3a699a72d8cfe26fde1bbb8fde5c1c8aaf
license    : MIT
component  : programming.library
summary    : Highly Optimized Graphics Math (GLM) for C
description: |
    cglm is optimized 3D math library written in C99 (compatible with C89). It is similar to original GLM library except this is mainly for C.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
