name       : cglm
version    : 0.8.4
release    : 3
source     :
    - https://github.com/recp/cglm/archive/refs/tags/v0.8.4.tar.gz : 42f84c42c8a3e62954da77ab5c5d3264033d5802009e175db7921332a476126e
license    : MIT
component  : programming.library
summary    : Highly Optimized Graphics Math (GLM) for C
description: |
    cglm is optimized 3D math library written in C99 (compatible with C89). It is similar to original GLM library except this is mainly for C.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
