name       : cglm
version    : 0.8.7
release    : 6
source     :
    - https://github.com/recp/cglm/archive/refs/tags/v0.8.7.tar.gz : c7022e3e8973cdd96393c251e08e4f136f327d11f64b4c63cf6ea69bf0c0963f
license    : MIT
component  : programming.library
summary    : Highly Optimized Graphics Math (GLM) for C
description: |
    cglm is optimized 3D math library written in C99 (compatible with C89). It is similar to original GLM library except this is mainly for C.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
